version: "3.7"

networks:
  proxy:
    external:
      name: infra_proxy

services:
  grocy:
    image: linuxserver/grocy
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${SERVICES_FOLDER}/grocy:/config
    networks:
      - proxy
    # ports:
      # - 9283:9283
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grocy.rule=Host(`grocy.$INTERNAL_HOST`)"
        - "traefik.http.routers.grocy.entrypoints=web"
